version: '3.3'
services:
  karmabot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: karmabot
#    image: 
    environment:
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_SECRET=${REDDIT_SECRET}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
    volumes:
      - "./src:/reddit-karma-bot-run"
    restart: unless-stopped

